package com.influencer.content.domain;

import jakarta.persistence.*;
import java.time.Instant;
import java.util.UUID;

/**
 * A domain the BRAND owns and has pointed at our hosting (roadmap Phase E).
 *
 * There is no price, order or payment column, and that is decision #9: the brand purchases on
 * their own registrar account and the platform never resells. Hosting is always ours (#10), so
 * there is no "point this at your own server" option either.
 */
@Entity
@Table(name = "brand_domains")
public class BrandDomain {
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "brand_id", nullable = false, updatable = false)
    private UUID brandId;

    @Column(name = "domain_name", nullable = false, updatable = false)
    private String domainName;

    /** pending -> verifying -> active | failed. DNS is not instant, so this is a state. */
    @Column(name = "dns_status", nullable = false)
    private String dnsStatus;

    /** Generated by the service, never accepted from a caller. */
    @Column(name = "verification_token", nullable = false, updatable = false)
    private String verificationToken;

    @Column(name = "verified_at")
    private Instant verifiedAt;

    @Column(name = "ssl_status", nullable = false)
    private String sslStatus;

    @Column(name = "ssl_issued_at")
    private Instant sslIssuedAt;

    @Column(name = "landing_template_id")
    private UUID landingTemplateId;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at")
    private Instant updatedAt;

    @PrePersist
    public void prePersist() {
        if (id == null) id = UUID.randomUUID();
        Instant now = Instant.now();
        if (createdAt == null) createdAt = now;
        if (dnsStatus == null) dnsStatus = "pending";
        if (sslStatus == null) sslStatus = "pending";
        updatedAt = now;
    }

    @PreUpdate
    public void preUpdate() { updatedAt = Instant.now(); }

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }
    public UUID getBrandId() { return brandId; }
    public void setBrandId(UUID brandId) { this.brandId = brandId; }
    public String getDomainName() { return domainName; }
    public void setDomainName(String domainName) { this.domainName = domainName; }
    public String getDnsStatus() { return dnsStatus; }
    public void setDnsStatus(String dnsStatus) { this.dnsStatus = dnsStatus; }
    public String getVerificationToken() { return verificationToken; }
    public void setVerificationToken(String verificationToken) { this.verificationToken = verificationToken; }
    public Instant getVerifiedAt() { return verifiedAt; }
    public void setVerifiedAt(Instant verifiedAt) { this.verifiedAt = verifiedAt; }
    public String getSslStatus() { return sslStatus; }
    public void setSslStatus(String sslStatus) { this.sslStatus = sslStatus; }
    public Instant getSslIssuedAt() { return sslIssuedAt; }
    public void setSslIssuedAt(Instant sslIssuedAt) { this.sslIssuedAt = sslIssuedAt; }
    public UUID getLandingTemplateId() { return landingTemplateId; }
    public void setLandingTemplateId(UUID landingTemplateId) { this.landingTemplateId = landingTemplateId; }
    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }
    public Instant getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(Instant updatedAt) { this.updatedAt = updatedAt; }
}
