-- =============================================================
-- Phase E: domains and hosting
-- Date: 2026-08-06
-- Roadmap: docs/landing-page-builder-roadmap.md §5 Phase E
--
-- The decisions this encodes (all 2026-08-02):
--
-- #9  THE BRAND PAYS THE REGISTRAR DIRECTLY. The platform never resells a domain. That removes
--     a reseller agreement, markup logic, billing integration and the awkward question of who
--     owns a domain when a brand leaves. So there is no price, no order and no payment column
--     here — this table records a domain the brand already owns and has pointed at us.
--
-- #10 HOSTING IS THE PLATFORM'S. A brand cannot point a domain at their own server, which keeps
--     SSL renewal, cache invalidation and rollback in one place where they can be made to work.
--
-- #11 TWO MONTHS FREE, FROM FIRST PUBLISH — not from signup. A brand that signs up, explores
--     for six weeks and then publishes should get the full window on the thing being trialled.
--     `hosting_expires_at` is therefore set on the first Published transition and left NULL
--     before it.
--
--     Modelled as a DATE THE PLATFORM CAN MOVE rather than a boolean `is_free`: a promotion is
--     then a bulk update, not a schema change.
--
-- AT EXPIRY A PAGE IS UNPUBLISHED, NOT DELETED. It stops serving and returns a clear expiry
-- response; the row, its blocks and its assets stay. Re-publishing after payment is a stage
-- change rather than a rebuild — deleting a brand's work because a trial lapsed is the kind of
-- thing that ends a customer relationship permanently.
--
-- Idempotent: safe to re-run.
-- =============================================================

begin;

-- -------------------------------------------------------------
-- 1. Hosting expiry on the page (decision #11).
-- -------------------------------------------------------------
alter table content.landing_templates
    add column if not exists hosting_expires_at timestamptz,
    add column if not exists first_published_at timestamptz;

comment on column content.landing_templates.hosting_expires_at is
    'When free hosting ends. NULL until the page is first published — the two-month window '
    'runs from first publish, not signup, so a brand gets the full trial on the thing being '
    'trialled. A date the platform can move, so a promotion is a bulk update not a schema change.';
comment on column content.landing_templates.first_published_at is
    'Set once, on the first Published transition. Distinct from updated_at, which moves on every '
    'edit and so cannot answer when the trial clock started.';

create index if not exists idx_landing_templates_expiry
    on content.landing_templates (hosting_expires_at)
    where hosting_expires_at is not null;

-- -------------------------------------------------------------
-- 2. Domains a brand has connected.
-- -------------------------------------------------------------
create table if not exists content.brand_domains (
    id                 uuid primary key default gen_random_uuid(),

    brand_id           uuid not null,

    -- Stored lowercase; a domain is case-insensitive and storing both cases would let the same
    -- domain be connected twice.
    domain_name        text not null,

    -- pending -> verifying -> active | failed. DNS is not instant and a brand needs to see
    -- where in the process they are, so this is a state rather than a boolean.
    dns_status         text not null default 'pending',

    -- The TXT record the brand must publish to prove they control the domain. Generated by us,
    -- never supplied by the caller: a caller-chosen token would let someone claim a domain by
    -- naming a record that already exists.
    verification_token text not null,
    verified_at        timestamptz,

    -- pending -> active | failed. Separate from DNS because a domain can be verified while its
    -- certificate is still issuing, and a brand seeing "active/pending" understands that.
    ssl_status         text not null default 'pending',
    ssl_issued_at      timestamptz,

    -- Which page this domain serves. Nullable: a brand may connect a domain before deciding
    -- what to put on it.
    landing_template_id uuid,

    created_at         timestamptz not null default now(),
    updated_at         timestamptz not null default now()
);

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'uq_brand_domains_name') then
        -- Globally unique, not per brand. Two brands cannot both serve example.com, and finding
        -- that out at DNS time rather than at connect time would be a confusing failure.
        alter table content.brand_domains add constraint uq_brand_domains_name unique (domain_name);
    end if;
    if not exists (select 1 from pg_constraint where conname = 'ck_brand_domains_dns_status') then
        alter table content.brand_domains add constraint ck_brand_domains_dns_status
            check (dns_status in ('pending','verifying','active','failed'));
    end if;
    if not exists (select 1 from pg_constraint where conname = 'ck_brand_domains_ssl_status') then
        alter table content.brand_domains add constraint ck_brand_domains_ssl_status
            check (ssl_status in ('pending','active','failed'));
    end if;
end $$;

create index if not exists idx_brand_domains_brand on content.brand_domains (brand_id);
create index if not exists idx_brand_domains_template
    on content.brand_domains (landing_template_id)
    where landing_template_id is not null;

comment on table content.brand_domains is
    'A domain the BRAND owns and has pointed at our hosting (decision #9 — the platform never '
    'resells domains, so there is no price or order here). Hosting is always ours (#10).';

commit;

-- ---------------------------------------------------------------
-- Verification (expect 0 and the two new columns):
--   select count(*) from content.brand_domains;
--   select column_name from information_schema.columns
--    where table_schema='content' and table_name='landing_templates'
--      and column_name in ('hosting_expires_at','first_published_at');
--
-- Rollback:
--   drop table if exists content.brand_domains;
--   alter table content.landing_templates
--       drop column if exists hosting_expires_at,
--       drop column if exists first_published_at;
--   -- Additive. Dropping hosting_expires_at makes every page host indefinitely again, which is
--   -- the pre-Phase-E behaviour; no page content is affected.
-- ---------------------------------------------------------------
