# One ECR repository per image.
#
# WHY ECR AND NOT TASK DEFINITIONS IN GIT. A task definition can only reference images by registry
# URI — there is no mechanism by which ECS pulls a build from a git repository, so the git-tag
# approach still needs a registry underneath it. The durable division is: git holds the source
# (these .tf files, the Dockerfiles), ECR holds the built artifacts, and the task definition is
# GENERATED by Terraform from both. That keeps one source of truth per thing.
#
# Traceability comes from the image tag: var.image_tag is the release tag, the same string
# scripts/build-and-push.sh pushed, and `latest` is rejected by a validation rule so a running task
# always names a specific build.

locals {
  # Service name -> the Maven module or build context it comes from. This map is the single place the
  # service list is written; ECR repositories, the container definitions and the build script all
  # derive from it, so adding a service is one entry rather than four edits.
  #
  # Ports match each service's application.properties default, which is also what the containers use
  # to reach each other over localhost inside the task.
  services = {
    dao            = { module = "InfluencerDAO", port = 8443 }
    web-experience = { module = "InfluencerWebExperience", port = 8081 }
    dps            = { module = "InfluencerPresentationService", port = 8090 }
    workflow       = { module = "InfluencerWorkflowService", port = 8444 }
    identity       = { module = "InfluencerIdentityService", port = 8445 }
    creator        = { module = "InfluencerCreatorService", port = 8446 }
    campaign       = { module = "InfluencerCampaignService", port = 8447 }
    attribution    = { module = "InfluencerAttributionService", port = 8448 }
    finance        = { module = "InfluencerFinanceService", port = 8449 }
    content        = { module = "InfluencerContentService", port = 8450 }
    # The agent builds from a different Dockerfile; module is unused for it.
    agent = { module = "", port = 8000 }
  }
}

resource "aws_ecr_repository" "service" {
  for_each = local.services

  name = "influencrm/${each.key}"

  # IMMUTABLE: pushing the same tag twice is rejected. This is the property that makes a rollback
  # meaningful — if v1.2.0 could be overwritten, "deploy v1.2.0" would not identify any particular
  # code, and rolling back to it could land somewhere new.
  image_tag_mutability = "IMMUTABLE"

  image_scanning_configuration {
    # Basic scanning is free and runs on push. It reports CVEs in the base image and the layers
    # above it; not acting on the result is a choice, but not having it is only ignorance.
    scan_on_push = true
  }

  encryption_configuration {
    encryption_type = "KMS"
    kms_key         = aws_kms_key.main.arn
  }

  tags = { Name = "influencrm-${each.key}" }
}

resource "aws_ecr_lifecycle_policy" "service" {
  for_each = aws_ecr_repository.service

  repository = each.value.name

  # Images are ~500-600MB each. Eleven services × every build kept forever is real money for layers
  # nothing will ever pull again. Ten is enough to roll back several releases.
  #
  # Untagged images are expired sooner and separately: they are the intermediate layers a failed or
  # superseded build leaves behind, and nothing can reference them.
  policy = jsonencode({
    rules = [
      {
        rulePriority = 1
        description  = "Expire untagged images after 3 days"
        selection = {
          tagStatus   = "untagged"
          countType   = "sinceImagePushed"
          countUnit   = "days"
          countNumber = 3
        }
        action = { type = "expire" }
      },
      {
        rulePriority = 2
        description  = "Keep the 10 most recent tagged images"
        selection = {
          tagStatus   = "any"
          countType   = "imageCountMoreThan"
          countNumber = 10
        }
        action = { type = "expire" }
      },
    ]
  })
}
