#!/usr/bin/env bash
# Populate the secrets Terraform creates EMPTY, because it cannot generate them.
#
#   ./infrastructure/scripts/bootstrap-secrets.sh prod us-east-1
#
# WHAT MUST BE SET OR NOTHING RUNS:
#   jwt-signing-key         the BFF refuses to start without it (an ephemeral key cannot be verified
#                           after a restart, which presents as intermittent auth failures)
#   dao-keystore-b64        the DAO refuses to start — server.ssl.key-store names a file
#   dao-keystore-password
#
# This script generates those three, because they are key material with a specific format rather than
# a credential issued by somebody else. Everything else — OAuth client secrets, the OpenAI key,
# Stripe, SES — must be pasted in by whoever holds it; the script prints the commands.
#
# WHY NOT IN TERRAFORM. A keystore generated by Terraform would live in state as a base64 blob and be
# regenerated on any provider quirk, silently invalidating the BFF's truststore. Generating it here,
# once, and putting it in Secrets Manager keeps rotation a deliberate act.
set -euo pipefail

ENVIRONMENT="${1:-prod}"
REGION="${2:-${AWS_REGION:-us-east-1}}"
PREFIX="influencrm-${ENVIRONMENT}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WORK="$(mktemp -d)"
# The keystore and the JWK are private keys. Remove them from disk whatever happens — including on
# an error partway through.
trap 'rm -rf "$WORK"' EXIT

put() {
    local name="$1" value="$2"
    aws secretsmanager put-secret-value \
        --secret-id "${PREFIX}/${name}" \
        --secret-string "$value" \
        --region "$REGION" \
        --output text --query VersionId >/dev/null
    echo "    set ${PREFIX}/${name}"
}

echo "==> environment ${ENVIRONMENT} in ${REGION}"
echo

# ---------------------------------------------------------------------------
# 1. The DAO's TLS keystore, and the BFF truststore that must match it
# ---------------------------------------------------------------------------
# SANs: `localhost` is the one that matters in a single task definition — every container shares one
# network namespace, so the BFF dials https://localhost:8443 and the certificate must be valid for
# that name. The others cover a future split into separate tasks.
echo "==> generating the DAO keystore"
KEYSTORE_PASSWORD="$(openssl rand -base64 24 | tr -d '\n/+=' | head -c 24)"

docker run --rm -v "${WORK}:/certs" eclipse-temurin:17-jdk sh -c "
    set -e
    keytool -genkeypair -alias influencerdao \
        -keyalg RSA -keysize 2048 -validity 825 \
        -storetype PKCS12 -keystore /certs/keystore.p12 -storepass '${KEYSTORE_PASSWORD}' \
        -dname 'CN=influencer-dao,OU=platform,O=influencrm,C=US' \
        -ext 'SAN=dns:localhost,dns:dao,dns:influencer-dao'
    keytool -exportcert -alias influencerdao -keystore /certs/keystore.p12 \
        -storetype PKCS12 -storepass '${KEYSTORE_PASSWORD}' -file /certs/dao-cert.crt
    keytool -importcert -noprompt -alias influencerdao -file /certs/dao-cert.crt \
        -keystore /certs/dao-truststore.p12 -storetype PKCS12 -storepass changeit
" >/dev/null

# -w0: base64 must be one line. A wrapped value survives the round-trip through Secrets Manager but
# the entrypoint's `base64 -d` is fine with newlines while some shells are not — one line removes the
# question entirely.
put "dao-keystore-b64" "$(base64 -w0 "${WORK}/keystore.p12")"
put "dao-keystore-password" "$KEYSTORE_PASSWORD"

# THE TRUSTSTORE IS PART OF THE IMAGE, NOT A SECRET. The BFF loads it from
# classpath:dao-truststore.p12, so a new keystore means rebuilding and redeploying the BFF image —
# otherwise it still trusts the OLD certificate and every DAO call fails verification, fail-closed.
cp "${WORK}/dao-truststore.p12" \
   "${REPO_ROOT}/InfluencerWebExperience/src/main/resources/dao-truststore.p12"
echo "    installed dao-truststore.p12 into the BFF resources"
echo "    >>> COMMIT IT AND REBUILD THE BFF IMAGE, or BFF -> DAO calls will fail verification."

# ---------------------------------------------------------------------------
# 2. The BFF's access-token signing key
# ---------------------------------------------------------------------------
# An RSA JWK including the private key — SigningKeySet parses it with nimbus and rejects a key with
# no private half, because it signs.
echo
echo "==> generating the JWT signing key"
openssl genrsa 2048 2>/dev/null > "${WORK}/jwt.pem"

JWK="$(python - "${WORK}/jwt.pem" <<'PY'
import base64, json, re, subprocess, sys
txt = subprocess.run(["openssl", "rsa", "-in", sys.argv[1], "-text", "-noout"],
                     capture_output=True, text=True).stdout
def grab(label):
    m = re.search(label + r":\s*\n((?:\s+[0-9a-f:]+\n)+)", txt)
    return bytes(int(b, 16) for b in m.group(1).replace("\n", "").replace(" ", "").strip(":").split(":") if b)
def b64u(b):
    return base64.urlsafe_b64encode(b.lstrip(b"\x00") or b"\x00").decode().rstrip("=")
e = int(re.search(r"publicExponent:\s*(\d+)", txt).group(1))
print(json.dumps({
    "kty": "RSA", "use": "sig", "alg": "RS256", "kid": "influencrm-1",
    "n": b64u(grab("modulus")),
    "e": b64u(e.to_bytes((e.bit_length() + 7) // 8, "big")),
    "d": b64u(grab("privateExponent")),
    "p": b64u(grab("prime1")), "q": b64u(grab("prime2")),
    "dp": b64u(grab("exponent1")), "dq": b64u(grab("exponent2")),
    "qi": b64u(grab("coefficient")),
}, separators=(",", ":")))
PY
)"
put "jwt-signing-key" "$JWK"

# ---------------------------------------------------------------------------
# 3. What only you can supply
# ---------------------------------------------------------------------------
cat <<EOF

==============================================================
The three blocking secrets are set. The platform will now START.

These remain EMPTY. Each fails CLOSED — the feature is unavailable and says so, rather than running
insecurely — so the platform is usable without them, but these features are not:

  # The OpenAI key. ROTATE THE ONE IN .env FIRST: it is a live key that sat in the working tree.
  aws secretsmanager put-secret-value --region ${REGION} \\
    --secret-id ${PREFIX}/openai-api-key --secret-string 'sk-...'
  # Unset: the agent falls back to deterministic matching, no LLM advice.

  # Google sign-in. The redirect URI must EXACTLY match what is registered in Cloud Console:
  #   <public_base_url>/api/auth/oauth/google/callback
  aws secretsmanager put-secret-value --region ${REGION} \\
    --secret-id ${PREFIX}/google-oauth-client-id --secret-string '...'
  aws secretsmanager put-secret-value --region ${REGION} \\
    --secret-id ${PREFIX}/google-oauth-client-secret --secret-string '...'

  # Facebook sign-in. Same exact-match rule, registered in Meta for Developers.
  aws secretsmanager put-secret-value --region ${REGION} \\
    --secret-id ${PREFIX}/facebook-oauth-client-id --secret-string '...'
  aws secretsmanager put-secret-value --region ${REGION} \\
    --secret-id ${PREFIX}/facebook-oauth-client-secret --secret-string '...'

  # Stripe. Unset: billing uses the 'manual' provider, which takes NO money and logs at WARN.
  aws secretsmanager put-secret-value --region ${REGION} \\
    --secret-id ${PREFIX}/stripe-secret-key --secret-string 'sk_live_...'
  # The webhook endpoint 503s until this is set; the signature IS its authentication.
  aws secretsmanager put-secret-value --region ${REGION} \\
    --secret-id ${PREFIX}/billing-webhook-secret --secret-string 'whsec_...'

  # SES. Unset: email provider stays 'log' — invitations reach NOBODY and nothing on screen says so.
  # The from address must be a verified SES identity in ${REGION}.
  aws secretsmanager put-secret-value --region ${REGION} \\
    --secret-id ${PREFIX}/ses-access-key-id --secret-string 'AKIA...'
  aws secretsmanager put-secret-value --region ${REGION} \\
    --secret-id ${PREFIX}/ses-secret-access-key --secret-string '...'

  # YouTube. Unset: subscriber counts stay simulated, recorded as source=mock.
  aws secretsmanager put-secret-value --region ${REGION} \\
    --secret-id ${PREFIX}/youtube-api-key --secret-string '...'

A secret change is only picked up when a task starts, so after setting these:
  aws ecs update-service --cluster ${PREFIX}-cluster --service ${PREFIX}-platform \\
    --force-new-deployment --region ${REGION}
==============================================================
EOF
