package com.influencer.webe.content.application;

/**
 * Where asset bytes live (roadmap B.1).
 *
 * <p>A port rather than a direct S3 call because the storage backend is an operational
 * decision that changes: local development has no S3, and production may move between
 * S3, a compatible provider, or a CDN-fronted bucket. None of that should reach the
 * upload endpoint or the builder.
 *
 * <p><b>Keys are generated by the implementation, not the caller.</b> A caller-supplied
 * key is a path-traversal and a cross-tenant overwrite waiting to happen — a request could
 * name another brand's key and replace its image. {@link #put} therefore takes the brand
 * and a display name and returns the key it chose.
 */
public interface AssetStoragePort {

    /**
     * Store bytes and return the generated storage key.
     *
     * @param brandId  owning tenant — becomes part of the key so objects are segregated
     * @param fileName the user's file name, used only for its extension and for display
     * @param contentType MIME type as validated by the caller
     * @param bytes    the object content
     * @return the storage key, unique across the bucket
     */
    String put(String brandId, String fileName, String contentType, byte[] bytes);

    /**
     * Resolve the URL a browser should load this asset from.
     *
     * <p>Returned rather than constructed by callers so that moving behind a CDN, or
     * switching to signed URLs with an expiry, is a change here and nowhere else.
     */
    String urlFor(String storageKey);

    /**
     * Read an object back.
     *
     * <p>Needed by the local filesystem adapter, which has no public URL of its own and
     * serves bytes through the application. An S3/CDN deployment would not use this path.
     *
     * @return the bytes, or null when the key is unknown
     */
    byte[] get(String storageKey);

    /** Remove an object. Idempotent: deleting an absent key is not an error. */
    void delete(String storageKey);
}
