package com.influencer.webe.content.infrastructure;

import com.influencer.webe.content.application.AssetStoragePort;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Locale;
import java.util.UUID;

/**
 * Local-disk asset storage — the default when no object store is configured.
 *
 * <p><b>Why this exists rather than requiring MinIO.</b> Phase B is a prerequisite for every
 * visual feature, and gating it on running a container would mean nothing downstream could
 * be built or tested until that container existed. The port is what matters architecturally;
 * this adapter makes it usable today, and {@code S3AssetStorage} takes over by configuration
 * with no code change elsewhere.
 *
 * <p>Not intended for production: files land on one machine's disk, so a second instance
 * would not see them. That is a deliberate limitation of the local adapter, not of the port.
 */
@Component
@ConditionalOnProperty(name = "web-experience.assets.provider", havingValue = "filesystem", matchIfMissing = true)
public class FilesystemAssetStorage implements AssetStoragePort {
    private static final Logger log = LoggerFactory.getLogger(FilesystemAssetStorage.class);

    private final Path root;
    private final String publicPrefix;

    public FilesystemAssetStorage(
            @Value("${web-experience.assets.filesystem.root:./asset-store}") String root,
            @Value("${web-experience.assets.public-prefix:/assets}") String publicPrefix) {
        this.root = Paths.get(root).toAbsolutePath().normalize();
        this.publicPrefix = publicPrefix;
        try {
            Files.createDirectories(this.root);
        } catch (IOException e) {
            throw new IllegalStateException("Cannot create asset store at " + this.root, e);
        }
        log.info("Asset storage: filesystem at {}", this.root);
    }

    @Override
    public String put(String brandId, String fileName, String contentType, byte[] bytes) {
        // The key is generated here and never taken from the caller: a caller-supplied key
        // could traverse out of the brand prefix or overwrite another tenant's object.
        String key = brandId + "/" + UUID.randomUUID() + extensionOf(fileName);
        Path target = resolveWithinRoot(key);
        try {
            Files.createDirectories(target.getParent());
            Files.write(target, bytes);
        } catch (IOException e) {
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Could not store asset");
        }
        return key;
    }

    @Override
    public String urlFor(String storageKey) {
        return publicPrefix + "/" + storageKey;
    }

    @Override
    public byte[] get(String storageKey) {
        Path target = resolveWithinRoot(storageKey);
        try {
            return Files.exists(target) ? Files.readAllBytes(target) : null;
        } catch (IOException e) {
            return null;
        }
    }

    @Override
    public void delete(String storageKey) {
        try {
            Files.deleteIfExists(resolveWithinRoot(storageKey));
        } catch (IOException ignored) {
            // Idempotent by contract; a failed delete leaves an orphan, not a broken state.
        }
    }

    /**
     * Resolve a key under the root and refuse anything that escapes it.
     *
     * <p>Keys are generated by {@link #put}, but {@link #get} and {@link #delete} take a key
     * that ultimately came from a database row, and a row is not a trust boundary. Checking
     * here means a malformed or tampered key cannot read {@code ../../etc/passwd}.
     */
    private Path resolveWithinRoot(String storageKey) {
        Path resolved = root.resolve(storageKey).normalize();
        if (!resolved.startsWith(root)) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid asset key");
        }
        return resolved;
    }

    /** Lowercased extension including the dot, or empty. Length-capped to avoid junk keys. */
    private String extensionOf(String fileName) {
        if (fileName == null) {
            return "";
        }
        int dot = fileName.lastIndexOf('.');
        if (dot < 0 || dot == fileName.length() - 1) {
            return "";
        }
        String ext = fileName.substring(dot).toLowerCase(Locale.ROOT);
        return ext.matches("\\.[a-z0-9]{1,8}") ? ext : "";
    }
}
